package com.draico.asvappra.opencl;

public class Device {
    private int currentDevice;
    private int currentSubDevice;
    private Platform currentPlatform;
    private boolean isDevicePartition;
    public static int DEVICE_TYPE_DEFAULT = 1 << 0;
    public static int DEVICE_TYPE_CPU = 1 << 1;
    public static int DEVICE_TYPE_GPU = 1 << 2;
    public static int DEVICE_TYPE_ACCELERATOR = 1 << 3;
    public static int DEVICE_TYPE_CUSTOM = 1 << 4;
    public static int DEVICE_TYPE_ALL = 0xFFFFFFFF;
    public static int PARTITION_EQUALLY = 0x1086;
    public static int PARTITION_BY_COUNTS = 0x1087;
    public static int PARTITION_BY_AFFINITY_DOMAIN = 0x1088;
    public static int AFFINITY_DOMAIN_NUMA = 1 << 0;
    public static int AFFINITY_DOMAIN_L4_CACHE = 1 << 1;
    public static int AFFINITY_DOMAIN_L3_CACHE = 1 << 2;
    public static int AFFINITY_DOMAIN_L2_CACHE = 1 << 3;
    public static int AFFINITY_DOMAIN_L1_CACHE = 1 << 4;
    public static int AFFINITY_DOMAIN_NEXT_PARTITIONABLE = 1 << 5;
    public static native Device[] getDevices(Platform platform, int deviceType);
    public native Device[] createPartition(int partitionType, int affinityType);
    public native String getType();
    public native int getVendorId();
    public native int getMaxComputeUnits();
    public native int getMaxWorkItemDimensions();
    public native int[] getMaxWorkItemSizes();
    public native int getMaxWorkGroupSize();
    public native int getPreferredVectorWidthChar();
    public native int getPreferredVectorWidthShort();
    public native int getPreferredVectorWidthInt();
    public native int getPreferredVectorWidthLong();
    public native int getPreferredVectorWidthFloat();
    public native int getPreferredVectorWidthDouble();
    public native int getPreferredVectorWidthHalf();
    public native int getNativeVectorWidthChar();
    public native int getNativeVectorWidthShort();
    public native int getNativeVectorWidthInt();
    public native int getNativeVectorWidthLong();
    public native int getNativeVectorWidthFloat();
    public native int getNativeVectorWidthDouble();
    public native int getNativeVectorWidthHalf();
    public native int getMaxClockFrequency();
    public native int getAddressBits();
    public native long getMaxMemAllocSize();
    public native boolean getImageSupport();
    public native int getMaxReadImageArgs();
    public native int getMaxWriteImageArgs();
    public native int getMaxReadWriteImageArgs();
    public native String getILVersion();
    public native int getImage2DMaxWidth();
    public native int getImage2DMaxHeight();
    public native int getImage3DMaxWidth();
    public native int getImage3DMaxHeight();
    public native int getImage3DMaxDepth();
    public native int getImageMaxBufferSize();
    public native int getImageMaxArraySize();
    public native int getMaxSamplers();
    public native int getImagePitchAlignment();
    public native int getImageBaseAddressAlignment();
    public native int getMaxPipeArgs();
    public native int getPipeMaxActiveReservations();
    public native int getPipeMaxPacketSize();
    public native int getMaxParameterSize();
    public native int getMemBaseAddressAlign();
    public native String getSingleFPConfig();
    public native String getDoubleFPConfig();
    public native String getGlobalMemCacheType();
    public native int getGlobalMemCachelineSize();
    public native long getGlobalMemCacheSize();
    public native String getLocalMemType();
    public native long getGlobalMemSize();
    public native boolean getErrorCorrectionSupport();
    public native long getMaxConstantBufferSize();
    public native int getMaxConstantArgs();
    public native int getMaxGlobalVariableSize();
    public native int getGlobalVariablePreferredTotalSize();
    public native long getLocalMemSize();
    public native int getProfilingTimerResolution();
    public native boolean getEndianLittle();
    public native boolean getAvailable();
    public native boolean getCompilerAvailable();
    public native boolean getLinkerAvailable();
    public native String getExecutionCapabilities();
    public native String getQueueOnHostProperties();
    public native String getQueueOnDeviceProperties();
    public native int getQueueOnDevicePreferredSize();
    public native int getQueueOnDeviceMaxSize();
    public native int getMaxOnDeviceQueues();
    public native int getMaxOnDeviceEvents();
    public native String getBuildInKernels();
    public native Platform getPlatform();
    public native String getName();
    public native String getVendor();
    public native String getDriverVersion();
    public native String getProfile();
    public native String getVersion();
    public native String getOpenCL_C_Version();
    public native String getExtensions();
    public native int getPrintfBufferSize();
    public native boolean getPreferredInteropUserSync();
    public native int getPartitionMaxSubDevices();
    public native String getPartitionProperties();
    public native String getPartitionAffinityDomain();
    public native String getPartitionType();
    public native int getReferenceCount();
    public native String getSVMCapabilities();
    public native int getPreferredPlatformAtomicAlignment();
    public native int getPreferredGlobalAtomicAlignment();
    public native int getPreferredLocalAtomicAlignment();
    public native int getMaxNumSubGroups();
    public native boolean getSubGroupIndependentForwardProgress();
    public native void releaseDevice();
    public native String toString();
}
